---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: portfolio-service

outputs:
- name: build-output

params:
  TERM: dumb

run:
  path: portfolio-service/ci/tasks/build-portfolio-service/task.sh
